import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'black beaded bracelet',
    price: 149,
    imageUrl: 'https://m.media-amazon.com/images/I/41NFvzoT6nL._UY1100_.jpg',
    category: 'Unisex',
    description: 'Sleek and minimalist, this bracelet features polished, glossy black beads. A versatile accessory perfect for any occasion, adding a touch of understated elegance to your look.',
    rating: 4.8,
    reviews: 120,
  },
  {
    id: 2,
    name: 'white Beaded Bracelet',
    price: 149,
    imageUrl: 'http://assets.myntassets.com/v1/assets/images/2025/JULY/24/AkOlhe0l_3cd23d3191ba4fd3b0172616eacf499a.jpg ',
    category: 'Women',
    description: 'A chic duo of bracelets featuring pristine white beads. This set combines a classic all-white strand with a complementary mixed-bead design, perfect for a fresh, layered style.',
    rating: 4.9,
    reviews: 95,
  },
  {
    id: 3,
    name: 'blue beaded bracelet',
    price: 179,
    imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQHKEsqeb5ueiRm1HBSCahneKgqYOOqakBxZ4tynr9LUeix4ZYcGEkDMlnur2jzL4NWlHzrGzkMzVOqzK6cdrzklrlaFJPiCkHXPYHxH4l-REyrgupRszMddA',
    category: 'Men',
    description: 'Embrace calm and style with this bracelet made of deep blue matte beads. A single, contrasting silver-accented bead provides a focal point, making it a sophisticated and modern accessory.',
    rating: 4.7,
    reviews: 88,
  },
  {
    id: 4,
    name: 'pink beaded bracelet',
    price: 199,
    imageUrl: 'https://m.media-amazon.com/images/I/31fxNiKsy1L._UY1100_.jpg ',
    category: 'Women',
    description: 'Add a soft touch of color with this lovely bracelet, featuring delicate, light pink beads. Its simple elegance makes it a perfect accessory for everyday wear or special occasions.',
    rating: 5.0,
    reviews: 150,
  },
  {
    id: 5,
    name: 'California dented golden beaded bracelet',
    price: 100,
    imageUrl: 'https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2025/APRIL/29/rNVEqAdp_c9d572c9f8044d9a8f8d8f1f6bdd8e18.jpg',
    category: 'Men',
    description: 'Make a bold statement with this stunning gold-toned bracelet. Featuring uniquely textured, hammered links, it catches the light beautifully, offering a modern and luxurious feel.',
    rating: 4.6,
    reviews: 112,
  },
  {
    id: 6,
    name: 'Silver Starlight beaded Bracelet',
    price: 50,
    imageUrl: 'https://images-cdn.ubuy.co.in/6839ba518aab6bfb780f37dc-sterling-silver-10mm-round-ball-bead.jpg',
    category: 'Women',
    description: 'A delicate silver-tone bracelet adorned with brilliant, sparkling beads that catch the light from every angle, creating a mesmerizing starlit effect on your wrist.',
    rating: 4.9,
    reviews: 75,
  },
  {
    id: 7,
    name: 'marroon Butterfly Charm',
    price: 159,
    imageUrl: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlb8HrHq58xFhwqxsUBl6yMrX1dtr1WtCIvFDvmHOEL9pIexktB7LCkTwc8xE2xuuzLF0J9XK-B62CGeLkFnBle5Ipc-2xqA',
    category: 'Unisex',
    description: 'A rich, maroon beaded bracelet centered with an exquisite golden butterfly charm. This piece combines earthy tones with a touch of elegance, perfect for a nature-inspired look.',
    rating: 4.5,
    reviews: 210,
  },
  {
    id: 8,
    name: ' colourful Butterfly Charm',
    price: 159,
    imageUrl: 'https://m.media-amazon.com/images/I/51rued15-3L._SY695_.jpg',
    category: 'Men',
    description: 'Brighten your day with this playful and colorful bracelet. A delightful mix of pastel-colored beads is complemented by a delicate silver butterfly charm, creating a fun and whimsical accessory.',
    rating: 4.8,
    reviews: 65,
  },
];